"""Small, reviewed reference catalog used when the API is offline.

Nutrients are expressed per 100 g. FoodData Central records are CC0 and each
entry keeps its FDC identifier so a user can inspect the exact source.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class FoodReference:
    key: str
    name: str
    aliases: tuple[str, ...]
    calories: float
    protein: float
    carbs: float
    fat: float
    fdc_id: int
    source_description: str
    piece_grams: Optional[float] = None
    piece_variance: float = 0.12
    density_g_ml: Optional[float] = None
    density_variance: float = 0.12


FOODS: tuple[FoodReference, ...] = (
    FoodReference(
        "kidney_beans",
        "Cooked kidney beans",
        ("rajma", "kidney bean", "red bean"),
        127,
        8.67,
        22.8,
        0.5,
        175194,
        "Beans, kidney, red, mature seeds, cooked, boiled, without salt",
        density_g_ml=0.75,
        density_variance=0.18,
    ),
    FoodReference(
        "lentils",
        "Cooked lentils",
        ("dal", "dhal", "lentil"),
        116,
        9.02,
        20.1,
        0.38,
        172421,
        "Lentils, mature seeds, cooked, boiled, without salt",
        density_g_ml=0.75,
        density_variance=0.18,
    ),
    FoodReference(
        "white_rice",
        "Cooked white rice",
        ("white rice", "plain rice", "cooked rice", "rice"),
        130,
        2.69,
        28.2,
        0.28,
        168878,
        "Rice, white, long-grain, regular, enriched, cooked",
        density_g_ml=0.79,
        density_variance=0.12,
    ),
    FoodReference(
        "roti",
        "Whole-wheat roti",
        ("chapati", "chappati", "phulka", "roti"),
        299,
        7.85,
        46.1,
        9.2,
        174075,
        "Bread, chapati or roti, whole wheat, commercially prepared, frozen",
        piece_grams=40,
        piece_variance=0.2,
    ),
    FoodReference(
        "chicken_breast",
        "Roasted chicken breast",
        ("chicken breast", "grilled chicken", "roasted chicken"),
        165,
        31,
        0,
        3.57,
        171477,
        "Chicken, broilers or fryers, breast, meat only, cooked, roasted",
    ),
    FoodReference(
        "boiled_egg",
        "Boiled egg",
        ("hard boiled egg", "boiled egg", "egg"),
        155,
        12.6,
        1.12,
        10.6,
        173424,
        "Egg, whole, cooked, hard-boiled",
        piece_grams=50,
        piece_variance=0.12,
    ),
    FoodReference(
        "whole_milk",
        "Whole milk",
        ("whole milk", "full fat milk", "milk"),
        60,
        3.27,
        4.63,
        3.2,
        746782,
        "Milk, whole, 3.25% milkfat, with added vitamin D",
        density_g_ml=1.03,
        density_variance=0.03,
    ),
    FoodReference(
        "plain_yogurt",
        "Plain whole-milk yogurt",
        ("plain yogurt", "yogurt", "curd", "dahi"),
        61,
        3.47,
        4.66,
        3.25,
        171284,
        "Yogurt, plain, whole milk",
        density_g_ml=1.03,
        density_variance=0.06,
    ),
    FoodReference(
        "banana",
        "Banana",
        ("banana", "kela"),
        89,
        1.09,
        22.8,
        0.33,
        173944,
        "Bananas, raw",
        piece_grams=118,
        piece_variance=0.18,
    ),
    FoodReference(
        "whole_wheat_bread",
        "Whole-wheat bread",
        ("whole wheat bread", "brown bread", "bread", "toast"),
        252,
        12.4,
        42.7,
        3.5,
        172688,
        "Bread, whole-wheat, commercially prepared",
        piece_grams=28,
        piece_variance=0.18,
    ),
    FoodReference(
        "peanut_butter",
        "Smooth peanut butter",
        ("peanut butter",),
        598,
        22.2,
        22.3,
        51.4,
        172470,
        "Peanut butter, smooth style, without salt",
        density_g_ml=1.07,
        density_variance=0.08,
    ),
    FoodReference(
        "idli",
        "Idli",
        ("idli", "idlis"),
        128,
        6.36,
        24.98,
        0.35,
        2708346,
        "Idli",
        piece_grams=50,
        piece_variance=0.22,
    ),
    FoodReference(
        "plain_dosa",
        "Plain dosa",
        ("plain dosa", "dosa"),
        210,
        5.7,
        37.04,
        4.05,
        2708347,
        "Dosa, plain",
        piece_grams=100,
        piece_variance=0.3,
    ),
    FoodReference(
        "chickpeas",
        "Boiled chickpeas",
        ("chickpeas", "chickpea", "chana", "chole", "garbanzo"),
        164,
        8.86,
        27.4,
        2.59,
        173757,
        "Chickpeas (garbanzo beans, bengal gram), mature seeds, cooked, boiled, without salt",
        density_g_ml=0.66,
        density_variance=0.15,
    ),
    FoodReference(
        "tofu",
        "Tofu (regular)",
        ("tofu",),
        76,
        8.1,
        1.9,
        4.8,
        172476,
        "Tofu, raw, regular, prepared with calcium sulfate",
        density_g_ml=1.04,
        density_variance=0.08,
    ),
    FoodReference(
        "brown_rice",
        "Cooked brown rice",
        ("brown rice",),
        123,
        2.74,
        25.6,
        0.97,
        169704,
        "Rice, brown, long-grain, cooked",
        density_g_ml=0.78,
        density_variance=0.12,
    ),
    FoodReference(
        "oats",
        "Rolled oats (dry)",
        ("rolled oats", "oatmeal", "oats"),
        379,
        13.2,
        67.7,
        6.5,
        173904,
        "Cereals, oats, regular and quick, not fortified, dry",
        density_g_ml=0.35,
        density_variance=0.15,
    ),
    FoodReference(
        "paratha",
        "Whole-wheat paratha",
        ("paratha", "parantha"),
        326,
        6.4,
        45.4,
        13.2,
        174076,
        "Bread, paratha, whole wheat, commercially prepared, frozen",
        piece_grams=80,
        piece_variance=0.25,
    ),
    FoodReference(
        "egg_white",
        "Egg white",
        ("egg whites", "egg white"),
        52,
        10.9,
        0.73,
        0.17,
        172183,
        "Egg, white, raw, fresh",
        piece_grams=33,
        piece_variance=0.12,
        density_g_ml=1.03,
        density_variance=0.05,
    ),
    FoodReference(
        "paneer",
        "Paneer (fresh cheese)",
        ("paneer",),
        310,
        20.4,
        2.5,
        24.3,
        172224,
        "Cheese, white, queso blanco (closest USDA analog to fresh paneer)",
    ),
    FoodReference(
        "butter",
        "Butter",
        ("makhan", "makkhan", "butter"),
        717,
        0.85,
        0.06,
        81.1,
        173430,
        "Butter, without salt",
        piece_grams=14,
        piece_variance=0.25,
        density_g_ml=0.96,
        density_variance=0.03,
    ),
    FoodReference(
        "olive_oil",
        "Olive oil",
        ("olive oil", "cooking oil", "oil"),
        884,
        0.0,
        0.0,
        100.0,
        171413,
        "Oil, olive, salad or cooking",
        density_g_ml=0.91,
        density_variance=0.02,
    ),
    FoodReference(
        "almonds",
        "Almonds",
        ("almonds", "almond", "badam"),
        579,
        21.15,
        21.55,
        49.93,
        170567,
        "Nuts, almonds",
        piece_grams=1.2,
        piece_variance=0.15,
        density_g_ml=0.55,
        density_variance=0.15,
    ),
    FoodReference(
        "boiled_potato",
        "Boiled potato",
        ("boiled potato", "potatoes", "potato", "aloo"),
        87,
        1.9,
        20.1,
        0.1,
        170438,
        "Potatoes, boiled, cooked in skin, flesh, without salt",
        piece_grams=170,
        piece_variance=0.25,
    ),
    FoodReference(
        "sweet_potato",
        "Baked sweet potato",
        ("sweet potato", "shakarkandi"),
        90,
        2.0,
        20.7,
        0.15,
        168483,
        "Sweet potato, cooked, baked in skin, flesh, without salt",
        piece_grams=150,
        piece_variance=0.25,
    ),
    FoodReference(
        "apple",
        "Apple",
        ("apple", "seb"),
        52,
        0.26,
        13.8,
        0.17,
        171688,
        "Apples, raw, with skin",
        piece_grams=182,
        piece_variance=0.2,
    ),
    FoodReference(
        "samosa",
        "Samosa",
        ("samosa", "samosas"),
        309,
        5.1,
        33.1,
        17.4,
        2344214,
        "Samosa (FNDDS survey recipe)",
        piece_grams=100,
        piece_variance=0.3,
    ),
    FoodReference(
        "biryani",
        "Biryani with meat",
        ("chicken biryani", "mutton biryani", "biryani"),
        144,
        8.4,
        12.1,
        6.8,
        2341916,
        "Biryani with meat (FNDDS survey recipe)",
        density_g_ml=0.85,
        density_variance=0.18,
    ),
    FoodReference(
        "chicken_curry",
        "Chicken curry",
        ("chicken curry", "chicken gravy"),
        82,
        5.7,
        6.7,
        3.9,
        2341861,
        "Chicken curry (FNDDS survey recipe)",
        density_g_ml=0.95,
        density_variance=0.15,
    ),
)


# Composite dishes whose parts would otherwise partially match the catalog
# (e.g. "butter chicken" would hit the butter record). These must go through
# the label-calories path or a clarification instead of a wrong match.
COMPLEX_DISHES: tuple[str, ...] = (
    "butter chicken",
    "paneer tikka",
    "palak paneer",
    "shahi paneer",
    "kadai paneer",
    "tikka masala",
    "fried rice",
    "noodle",
    "maggi",
    "pizza",
    "burger",
    "pasta",
    "sandwich",
    "milkshake",
    "smoothie",
    "pav bhaji",
    "chole bhature",
    "masala dosa",
)


def find_food(name: str) -> Optional[FoodReference]:
    normalized = name.casefold().strip()
    if any(dish in normalized for dish in COMPLEX_DISHES):
        return None
    candidates = [
        food
        for food in FOODS
        if food.key == normalized
        or food.name.casefold() == normalized
        or any(alias in normalized or normalized in alias for alias in food.aliases)
    ]
    if not candidates:
        return None
    return max(
        candidates,
        key=lambda food: max(
            [len(alias) for alias in food.aliases if alias in normalized or normalized in alias]
            or [0]
        ),
    )
