/**
 * Real demonstration photo pairs (start / end position) for built-in
 * exercises. Photos are from the free-exercise-db project (public domain,
 * https://github.com/yuhonas/free-exercise-db). GENERATED file.
 */

export const EXERCISE_PHOTOS: Record<string, [number, number]> = {
  'ab-wheel-rollout': [require('../../assets/exercises/ab-wheel-rollout-0.jpg'), require('../../assets/exercises/ab-wheel-rollout-1.jpg')],
  'back-extension': [require('../../assets/exercises/back-extension-0.jpg'), require('../../assets/exercises/back-extension-1.jpg')],
  'barbell-curl': [require('../../assets/exercises/barbell-curl-0.jpg'), require('../../assets/exercises/barbell-curl-1.jpg')],
  'barbell-row': [require('../../assets/exercises/barbell-row-0.jpg'), require('../../assets/exercises/barbell-row-1.jpg')],
  'barbell-shrug': [require('../../assets/exercises/barbell-shrug-0.jpg'), require('../../assets/exercises/barbell-shrug-1.jpg')],
  'bench-dip': [require('../../assets/exercises/bench-dip-0.jpg'), require('../../assets/exercises/bench-dip-1.jpg')],
  'bench-press': [require('../../assets/exercises/bench-press-0.jpg'), require('../../assets/exercises/bench-press-1.jpg')],
  'bicycle-crunch': [require('../../assets/exercises/bicycle-crunch-0.jpg'), require('../../assets/exercises/bicycle-crunch-1.jpg')],
  'bodyweight-squat': [require('../../assets/exercises/bodyweight-squat-0.jpg'), require('../../assets/exercises/bodyweight-squat-1.jpg')],
  'bulgarian-split-squat': [require('../../assets/exercises/bulgarian-split-squat-0.jpg'), require('../../assets/exercises/bulgarian-split-squat-1.jpg')],
  'cable-chest-fly': [require('../../assets/exercises/cable-chest-fly-0.jpg'), require('../../assets/exercises/cable-chest-fly-1.jpg')],
  'cable-crunch': [require('../../assets/exercises/cable-crunch-0.jpg'), require('../../assets/exercises/cable-crunch-1.jpg')],
  'cable-curl': [require('../../assets/exercises/cable-curl-0.jpg'), require('../../assets/exercises/cable-curl-1.jpg')],
  'cable-kickback': [require('../../assets/exercises/cable-kickback-0.jpg'), require('../../assets/exercises/cable-kickback-1.jpg')],
  'chest-dip': [require('../../assets/exercises/chest-dip-0.jpg'), require('../../assets/exercises/chest-dip-1.jpg')],
  'chinup': [require('../../assets/exercises/chinup-0.jpg'), require('../../assets/exercises/chinup-1.jpg')],
  'clean-and-press': [require('../../assets/exercises/clean-and-press-0.jpg'), require('../../assets/exercises/clean-and-press-1.jpg')],
  'close-grip-bench': [require('../../assets/exercises/close-grip-bench-0.jpg'), require('../../assets/exercises/close-grip-bench-1.jpg')],
  'concentration-curl': [require('../../assets/exercises/concentration-curl-0.jpg'), require('../../assets/exercises/concentration-curl-1.jpg')],
  'crunch': [require('../../assets/exercises/crunch-0.jpg'), require('../../assets/exercises/crunch-1.jpg')],
  'cycling': [require('../../assets/exercises/cycling-0.jpg'), require('../../assets/exercises/cycling-1.jpg')],
  'dead-bug': [require('../../assets/exercises/dead-bug-0.jpg'), require('../../assets/exercises/dead-bug-1.jpg')],
  'deadlift': [require('../../assets/exercises/deadlift-0.jpg'), require('../../assets/exercises/deadlift-1.jpg')],
  'diamond-pushup': [require('../../assets/exercises/diamond-pushup-0.jpg'), require('../../assets/exercises/diamond-pushup-1.jpg')],
  'dumbbell-bench-press': [require('../../assets/exercises/dumbbell-bench-press-0.jpg'), require('../../assets/exercises/dumbbell-bench-press-1.jpg')],
  'dumbbell-curl': [require('../../assets/exercises/dumbbell-curl-0.jpg'), require('../../assets/exercises/dumbbell-curl-1.jpg')],
  'dumbbell-fly': [require('../../assets/exercises/dumbbell-fly-0.jpg'), require('../../assets/exercises/dumbbell-fly-1.jpg')],
  'dumbbell-row': [require('../../assets/exercises/dumbbell-row-0.jpg'), require('../../assets/exercises/dumbbell-row-1.jpg')],
  'dumbbell-shoulder-press': [require('../../assets/exercises/dumbbell-shoulder-press-0.jpg'), require('../../assets/exercises/dumbbell-shoulder-press-1.jpg')],
  'dumbbell-shrug': [require('../../assets/exercises/dumbbell-shrug-0.jpg'), require('../../assets/exercises/dumbbell-shrug-1.jpg')],
  'elliptical': [require('../../assets/exercises/elliptical-0.jpg'), require('../../assets/exercises/elliptical-1.jpg')],
  'face-pull': [require('../../assets/exercises/face-pull-0.jpg'), require('../../assets/exercises/face-pull-1.jpg')],
  'farmers-carry': [require('../../assets/exercises/farmers-carry-0.jpg'), require('../../assets/exercises/farmers-carry-1.jpg')],
  'front-raise': [require('../../assets/exercises/front-raise-0.jpg'), require('../../assets/exercises/front-raise-1.jpg')],
  'front-squat': [require('../../assets/exercises/front-squat-0.jpg'), require('../../assets/exercises/front-squat-1.jpg')],
  'glute-bridge': [require('../../assets/exercises/glute-bridge-0.jpg'), require('../../assets/exercises/glute-bridge-1.jpg')],
  'goblet-squat': [require('../../assets/exercises/goblet-squat-0.jpg'), require('../../assets/exercises/goblet-squat-1.jpg')],
  'good-morning': [require('../../assets/exercises/good-morning-0.jpg'), require('../../assets/exercises/good-morning-1.jpg')],
  'hack-squat': [require('../../assets/exercises/hack-squat-0.jpg'), require('../../assets/exercises/hack-squat-1.jpg')],
  'hammer-curl': [require('../../assets/exercises/hammer-curl-0.jpg'), require('../../assets/exercises/hammer-curl-1.jpg')],
  'hanging-knee-raise': [require('../../assets/exercises/hanging-knee-raise-0.jpg'), require('../../assets/exercises/hanging-knee-raise-1.jpg')],
  'hanging-leg-raise': [require('../../assets/exercises/hanging-leg-raise-0.jpg'), require('../../assets/exercises/hanging-leg-raise-1.jpg')],
  'hip-abduction': [require('../../assets/exercises/hip-abduction-0.jpg'), require('../../assets/exercises/hip-abduction-1.jpg')],
  'hip-thrust': [require('../../assets/exercises/hip-thrust-0.jpg'), require('../../assets/exercises/hip-thrust-1.jpg')],
  'incline-bench-press': [require('../../assets/exercises/incline-bench-press-0.jpg'), require('../../assets/exercises/incline-bench-press-1.jpg')],
  'incline-dumbbell-curl': [require('../../assets/exercises/incline-dumbbell-curl-0.jpg'), require('../../assets/exercises/incline-dumbbell-curl-1.jpg')],
  'incline-dumbbell-press': [require('../../assets/exercises/incline-dumbbell-press-0.jpg'), require('../../assets/exercises/incline-dumbbell-press-1.jpg')],
  'jump-rope': [require('../../assets/exercises/jump-rope-0.jpg'), require('../../assets/exercises/jump-rope-1.jpg')],
  'kettlebell-swing': [require('../../assets/exercises/kettlebell-swing-0.jpg'), require('../../assets/exercises/kettlebell-swing-1.jpg')],
  'lat-pulldown': [require('../../assets/exercises/lat-pulldown-0.jpg'), require('../../assets/exercises/lat-pulldown-1.jpg')],
  'lateral-raise': [require('../../assets/exercises/lateral-raise-0.jpg'), require('../../assets/exercises/lateral-raise-1.jpg')],
  'leg-extension': [require('../../assets/exercises/leg-extension-0.jpg'), require('../../assets/exercises/leg-extension-1.jpg')],
  'leg-press': [require('../../assets/exercises/leg-press-0.jpg'), require('../../assets/exercises/leg-press-1.jpg')],
  'lying-leg-curl': [require('../../assets/exercises/lying-leg-curl-0.jpg'), require('../../assets/exercises/lying-leg-curl-1.jpg')],
  'lying-leg-raise': [require('../../assets/exercises/lying-leg-raise-0.jpg'), require('../../assets/exercises/lying-leg-raise-1.jpg')],
  'machine-chest-press': [require('../../assets/exercises/machine-chest-press-0.jpg'), require('../../assets/exercises/machine-chest-press-1.jpg')],
  'machine-row': [require('../../assets/exercises/machine-row-0.jpg'), require('../../assets/exercises/machine-row-1.jpg')],
  'machine-shoulder-press': [require('../../assets/exercises/machine-shoulder-press-0.jpg'), require('../../assets/exercises/machine-shoulder-press-1.jpg')],
  'mountain-climber': [require('../../assets/exercises/mountain-climber-0.jpg'), require('../../assets/exercises/mountain-climber-1.jpg')],
  'nordic-curl': [require('../../assets/exercises/nordic-curl-0.jpg'), require('../../assets/exercises/nordic-curl-1.jpg')],
  'outdoor-run': [require('../../assets/exercises/outdoor-run-0.jpg'), require('../../assets/exercises/outdoor-run-1.jpg')],
  'overhead-cable-extension': [require('../../assets/exercises/overhead-cable-extension-0.jpg'), require('../../assets/exercises/overhead-cable-extension-1.jpg')],
  'overhead-dumbbell-extension': [require('../../assets/exercises/overhead-dumbbell-extension-0.jpg'), require('../../assets/exercises/overhead-dumbbell-extension-1.jpg')],
  'overhead-press': [require('../../assets/exercises/overhead-press-0.jpg'), require('../../assets/exercises/overhead-press-1.jpg')],
  'pec-deck': [require('../../assets/exercises/pec-deck-0.jpg'), require('../../assets/exercises/pec-deck-1.jpg')],
  'plank': [require('../../assets/exercises/plank-0.jpg'), require('../../assets/exercises/plank-1.jpg')],
  'preacher-curl': [require('../../assets/exercises/preacher-curl-0.jpg'), require('../../assets/exercises/preacher-curl-1.jpg')],
  'pullup': [require('../../assets/exercises/pullup-0.jpg'), require('../../assets/exercises/pullup-1.jpg')],
  'pushup': [require('../../assets/exercises/pushup-0.jpg'), require('../../assets/exercises/pushup-1.jpg')],
  'rack-pull': [require('../../assets/exercises/rack-pull-0.jpg'), require('../../assets/exercises/rack-pull-1.jpg')],
  'rear-delt-fly': [require('../../assets/exercises/rear-delt-fly-0.jpg'), require('../../assets/exercises/rear-delt-fly-1.jpg')],
  'reverse-pec-deck': [require('../../assets/exercises/reverse-pec-deck-0.jpg'), require('../../assets/exercises/reverse-pec-deck-1.jpg')],
  'reverse-wrist-curl': [require('../../assets/exercises/reverse-wrist-curl-0.jpg'), require('../../assets/exercises/reverse-wrist-curl-1.jpg')],
  'romanian-deadlift': [require('../../assets/exercises/romanian-deadlift-0.jpg'), require('../../assets/exercises/romanian-deadlift-1.jpg')],
  'rowing-machine': [require('../../assets/exercises/rowing-machine-0.jpg'), require('../../assets/exercises/rowing-machine-1.jpg')],
  'russian-twist': [require('../../assets/exercises/russian-twist-0.jpg'), require('../../assets/exercises/russian-twist-1.jpg')],
  'seated-cable-row': [require('../../assets/exercises/seated-cable-row-0.jpg'), require('../../assets/exercises/seated-cable-row-1.jpg')],
  'seated-calf-raise': [require('../../assets/exercises/seated-calf-raise-0.jpg'), require('../../assets/exercises/seated-calf-raise-1.jpg')],
  'seated-leg-curl': [require('../../assets/exercises/seated-leg-curl-0.jpg'), require('../../assets/exercises/seated-leg-curl-1.jpg')],
  'side-plank': [require('../../assets/exercises/side-plank-0.jpg'), require('../../assets/exercises/side-plank-1.jpg')],
  'single-leg-calf-raise': [require('../../assets/exercises/single-leg-calf-raise-0.jpg'), require('../../assets/exercises/single-leg-calf-raise-1.jpg')],
  'skullcrusher': [require('../../assets/exercises/skullcrusher-0.jpg'), require('../../assets/exercises/skullcrusher-1.jpg')],
  'squat': [require('../../assets/exercises/squat-0.jpg'), require('../../assets/exercises/squat-1.jpg')],
  'stair-climber': [require('../../assets/exercises/stair-climber-0.jpg'), require('../../assets/exercises/stair-climber-1.jpg')],
  'standing-calf-raise': [require('../../assets/exercises/standing-calf-raise-0.jpg'), require('../../assets/exercises/standing-calf-raise-1.jpg')],
  'step-up': [require('../../assets/exercises/step-up-0.jpg'), require('../../assets/exercises/step-up-1.jpg')],
  'stiff-leg-deadlift': [require('../../assets/exercises/stiff-leg-deadlift-0.jpg'), require('../../assets/exercises/stiff-leg-deadlift-1.jpg')],
  'straight-arm-pulldown': [require('../../assets/exercises/straight-arm-pulldown-0.jpg'), require('../../assets/exercises/straight-arm-pulldown-1.jpg')],
  'sumo-deadlift': [require('../../assets/exercises/sumo-deadlift-0.jpg'), require('../../assets/exercises/sumo-deadlift-1.jpg')],
  'tbar-row': [require('../../assets/exercises/tbar-row-0.jpg'), require('../../assets/exercises/tbar-row-1.jpg')],
  'thruster': [require('../../assets/exercises/thruster-0.jpg'), require('../../assets/exercises/thruster-1.jpg')],
  'treadmill-run': [require('../../assets/exercises/treadmill-run-0.jpg'), require('../../assets/exercises/treadmill-run-1.jpg')],
  'triceps-pushdown': [require('../../assets/exercises/triceps-pushdown-0.jpg'), require('../../assets/exercises/triceps-pushdown-1.jpg')],
  'upright-row': [require('../../assets/exercises/upright-row-0.jpg'), require('../../assets/exercises/upright-row-1.jpg')],
  'walking': [require('../../assets/exercises/walking-0.jpg'), require('../../assets/exercises/walking-1.jpg')],
  'walking-lunge': [require('../../assets/exercises/walking-lunge-0.jpg'), require('../../assets/exercises/walking-lunge-1.jpg')],
  'wrist-curl': [require('../../assets/exercises/wrist-curl-0.jpg'), require('../../assets/exercises/wrist-curl-1.jpg')],
};

export function photosFor(exerciseId: string): [number, number] | undefined {
  return EXERCISE_PHOTOS[exerciseId];
}
