export const FEATURE_AREAS = [
  'onboarding', 'auth', 'password-recovery', 'offline-vault', 'cloud-sync',
  'today', 'quick-log', 'voice', 'food', 'learned-foods', 'saved-meals',
  'water', 'weight', 'health', 'goals', 'progress', 'coach', 'settings',
  'backup-restore', 'account-deletion', 'routines', 'exercise-library',
  'live-workout', 'timed-sets', 'rest-timer', 'workout-history',
  'apple-watch', 'accessibility',
] as const;

export type FeatureArea = typeof FEATURE_AREAS[number];

export type AgentPersona = {
  id: string;
  name: string;
  realLifeContext: string;
  devices: string;
  journey: string;
  features: FeatureArea[];
  suggestionPrompt: string;
  physicalDeviceRequired?: boolean;
};

export const AGENT_PERSONAS: AgentPersona[] = [
  { id: 'A01', name: 'Neha', realLifeContext: 'Sedentary Indian vegetarian beginning a fat-loss plan', devices: 'iPhone', journey: 'Create an account, confirm email, set current and lower target weight, accept then customize recommended targets, and log roti-dal in Hinglish.', features: ['onboarding', 'auth', 'goals', 'weight', 'voice', 'quick-log', 'food'], suggestionPrompt: 'Does the plan feel personally explained and culturally useful?' },
  { id: 'A02', name: 'Arjun', realLifeContext: 'Experienced powerlifter building muscle with RPE and supersets', devices: 'iPhone + Apple Watch', journey: 'Build a push routine, link a superset, log load/reps/RPE on Watch, finish, and inspect PRs and measured calories.', features: ['routines', 'exercise-library', 'live-workout', 'workout-history', 'apple-watch', 'health'], suggestionPrompt: 'What advanced set controls or history comparisons are missing?', physicalDeviceRequired: true },
  { id: 'A03', name: 'Aisha', realLifeContext: 'Vegan user with dairy and soy allergies', devices: 'Android', journey: 'Save dietary constraints, log almond milk and a vegan meal, ask Coach for a safe protein option, and review assumptions.', features: ['settings', 'food', 'quick-log', 'coach', 'learned-foods'], suggestionPrompt: 'Did any recommendation or match violate a dietary constraint?' },
  { id: 'A04', name: 'Ben', realLifeContext: 'Celiac student scanning unfamiliar packaged foods on a budget', devices: 'iPhone', journey: 'Log a gluten-free label food, teach its calories, rename it, and log it again without another clarification.', features: ['food', 'learned-foods', 'quick-log'], suggestionPrompt: 'What label fields and allergen safeguards should be added?' },
  { id: 'A05', name: 'Leena', realLifeContext: 'Physiotherapy patient using low-impact timed holds', devices: 'iPhone + Apple Watch', journey: 'Create a rehabilitation routine, run a 45-second plank, background and resume it, then verify the exact duration in history.', features: ['routines', 'timed-sets', 'live-workout', 'workout-history', 'apple-watch'], suggestionPrompt: 'Can custom rehab movements and pain notes be recorded safely?', physicalDeviceRequired: true },
  { id: 'A06', name: 'Priya', realLifeContext: 'Night-shift nurse whose meal names do not match normal clock times', devices: 'iPhone', journey: 'Repeat a saved breakfast during a night shift, change its meal slot, log water, and inspect the correct calendar day.', features: ['saved-meals', 'today', 'food', 'water'], suggestionPrompt: 'Does the app support non-standard schedules and meal editing?' },
  { id: 'A07', name: 'Omar', realLifeContext: 'Privacy-conscious user who wants local-only tracking', devices: 'Android', journey: 'Skip account creation, log a week offline, export a backup, restore it, and verify no account is required.', features: ['offline-vault', 'backup-restore', 'today', 'progress'], suggestionPrompt: 'Are privacy, storage, and recovery choices understandable?' },
  { id: 'A08', name: 'Lina', realLifeContext: 'Returning account holder who logged meals as a guest while signed out', devices: 'Two iPhones', journey: 'Create guest logs, sign into an existing vault, confirm both histories merge, then foreground the second phone and verify it pulls changes.', features: ['auth', 'offline-vault', 'cloud-sync', 'food'], suggestionPrompt: 'Was any data duplicated, delayed, or lost across devices?', physicalDeviceRequired: true },
  { id: 'A09', name: 'Daniel', realLifeContext: 'Distracted parent who often taps quick actions twice', devices: 'iPhone', journey: 'Repeat a saved meal twice, remove the duplicate, undo a water add, and correct today’s exact total downward.', features: ['saved-meals', 'food', 'water', 'today'], suggestionPrompt: 'Where are confirmation, undo, and edit controls still needed?' },
  { id: 'A10', name: 'Maya', realLifeContext: 'Macro-focused athlete using branded nutrition labels', devices: 'Android', journey: 'Enter label calories and macros for an unknown yogurt, review the operation, save it, and compare daily totals.', features: ['quick-log', 'food', 'learned-foods', 'progress'], suggestionPrompt: 'Are label macros, serving sizes, and confidence sufficiently editable?' },
  { id: 'A11', name: 'Raj', realLifeContext: 'Older user with an Indian accent and intermittent internet', devices: 'iPhone', journey: 'Use voice for weight, food, water, and steps; fall back to keyboard when recognition fails; relaunch offline.', features: ['voice', 'weight', 'quick-log', 'offline-vault', 'accessibility'], suggestionPrompt: 'Which words, labels, or tap targets are difficult?' },
  { id: 'A12', name: 'Asha', realLifeContext: 'VoiceOver user who strength trains independently', devices: 'iPhone + Apple Watch', journey: 'Navigate onboarding, auth, routine setup, set editing and deletion without visual context.', features: ['accessibility', 'onboarding', 'auth', 'routines', 'live-workout', 'apple-watch'], suggestionPrompt: 'Which controls are unlabeled, gesture-hidden, or presented in a confusing focus order?', physicalDeviceRequired: true },
  { id: 'A13', name: 'Sophia', realLifeContext: 'Large Dynamic Type user on a small Apple Watch', devices: 'iPhone SE + 40 mm Watch', journey: 'Run an eight-set workout, scroll KG/reps controls, finish it, and inspect Progress at 200% text size.', features: ['accessibility', 'apple-watch', 'live-workout', 'progress'], suggestionPrompt: 'Which actions clip, overlap, truncate, or become unreachable?', physicalDeviceRequired: true },
  { id: 'A14', name: 'Carla', realLifeContext: 'Strength athlete correcting an accidentally completed set', devices: 'Apple Watch', journey: 'Edit KG/reps, complete the wrong set, reopen it, correct it, and continue the routine.', features: ['apple-watch', 'live-workout'], suggestionPrompt: 'Are corrections possible without returning to the phone?', physicalDeviceRequired: true },
  { id: 'A15', name: 'Marcus', realLifeContext: 'Phone-led lifter relying on Watch heart rate and calories', devices: 'iPhone + Apple Watch', journey: 'Start on phone, watch live heart rate/calories, finish immediately after the last set, and verify final Health energy is retained.', features: ['health', 'apple-watch', 'live-workout', 'workout-history'], suggestionPrompt: 'Are sensor source, freshness, and measured-versus-estimated calories clear?', physicalDeviceRequired: true },
  { id: 'A16', name: 'Maya W', realLifeContext: 'Traveler who works out away from the phone', devices: 'Apple Watch offline', journey: 'Start, edit, pause, resume, and finish entirely on Watch; reconnect later and confirm one complete session.', features: ['apple-watch', 'offline-vault', 'live-workout', 'workout-history', 'cloud-sync'], suggestionPrompt: 'Which phone-only actions block a Watch-only session?', physicalDeviceRequired: true },
  { id: 'A17', name: 'Karan', realLifeContext: 'Home cook describing mixed dishes with one unknown ingredient', devices: 'Android', journey: 'Say “150 g rice and 100 g edamame,” review every detected and undetected part, then correct before saving.', features: ['quick-log', 'food', 'voice'], suggestionPrompt: 'Did the app ever silently omit part of the meal?' },
  { id: 'A18', name: 'Iris', realLifeContext: 'User moving to a new phone with a large history', devices: 'Two iPhones', journey: 'Export, restore into a populated account, resolve duplicates, sync, sign out, and sign back in.', features: ['backup-restore', 'cloud-sync', 'auth', 'progress'], suggestionPrompt: 'Is restore validation and conflict behavior trustworthy?', physicalDeviceRequired: true },
  { id: 'A19', name: 'Sam', realLifeContext: 'Hybrid athlete mixing weights and treadmill intervals', devices: 'iPhone + Apple Watch', journey: 'Run a mixed session with timed cardio and weighted sets, use rest timers, and inspect workout classification.', features: ['timed-sets', 'rest-timer', 'live-workout', 'health', 'apple-watch'], suggestionPrompt: 'Does mixed-workout classification and calorie tracking match reality?', physicalDeviceRequired: true },
  { id: 'A20', name: 'Fatima', realLifeContext: 'Busy parent logging after midnight and correcting past mistakes', devices: 'iPhone', journey: 'Log food, water, sleep and weight near midnight; clear a mistaken value to zero; inspect 7/30/90-day trends.', features: ['today', 'food', 'water', 'weight', 'progress'], suggestionPrompt: 'Is date ownership obvious and can old entries be edited?' },
  { id: 'A21', name: 'Elena', realLifeContext: 'Runner who denied one Health permission but allowed others', devices: 'iPhone + Apple Watch', journey: 'Connect Health with partial permissions, sync steps and active energy, and verify denied metrics do not claim success.', features: ['health', 'today', 'progress', 'apple-watch'], suggestionPrompt: 'Are permission state, source, sample freshness, and empty data clear?', physicalDeviceRequired: true },
  { id: 'A22', name: 'Noah', realLifeContext: 'Maintenance user with an older eight-character password', devices: 'iPhone', journey: 'Sign into an existing account, edit a maintenance target, change password, and verify the stated sign-out scope.', features: ['auth', 'password-recovery', 'goals', 'account-deletion'], suggestionPrompt: 'Are account security rules and session consequences explained?' },
  { id: 'A23', name: 'Grace', realLifeContext: 'New user whose confirmation email arrives late', devices: 'iPhone', journey: 'Sign up, resend confirmation, cold-open the deep link, sign in, request recovery, and set a new password.', features: ['auth', 'password-recovery', 'cloud-sync'], suggestionPrompt: 'Where can the email/deep-link flow leave the user stranded?', physicalDeviceRequired: true },
  { id: 'A24', name: 'Nikhil', realLifeContext: 'Interval athlete creating ad-hoc duration exercises', devices: 'Apple Watch', journey: 'Add a duration exercise on Watch, customize 75 seconds, pause/resume, and ensure its timer cannot complete another set.', features: ['exercise-library', 'timed-sets', 'apple-watch', 'live-workout'], suggestionPrompt: 'What timer controls and identity safeguards are missing?', physicalDeviceRequired: true },
  { id: 'A25', name: 'Meera', realLifeContext: 'Beginner who wants to correct wide portion estimates', devices: 'Android', journey: 'Open the widest food estimate, edit amount/calories/macros/slot, save it, and verify the range narrows.', features: ['food', 'quick-log', 'learned-foods'], suggestionPrompt: 'Can every important field be corrected before and after logging?' },
  { id: 'A26', name: 'George', realLifeContext: 'User intentionally choosing zero strength days during recovery', devices: 'iPhone', journey: 'Set weekly strength to zero, save, relaunch, and verify the value remains zero while other goals persist.', features: ['settings', 'goals', 'offline-vault'], suggestionPrompt: 'Do zero and empty values behave differently and predictably?' },
  { id: 'A27', name: 'Sara', realLifeContext: 'New gym member asking for a simple next action', devices: 'iPhone', journey: 'Ask Coach about dinner, protein, hydration and a beginner workout; relaunch and inspect conversation history.', features: ['coach', 'food', 'water', 'live-workout', 'offline-vault'], suggestionPrompt: 'Is advice specific, explainable, safe, and actionable?' },
  { id: 'A28', name: 'Ethan', realLifeContext: 'User cleaning history while keeping carefully built routines', devices: 'Android', journey: 'Clear fitness history, then verify profile, goals, routines, custom items and learned foods remain while logs disappear.', features: ['settings', 'routines', 'learned-foods', 'progress'], suggestionPrompt: 'Does destructive-action wording exactly match what is erased?' },
  { id: 'A29', name: 'Chloe', realLifeContext: 'User leaving the service and exercising data rights', devices: 'iPhone', journey: 'Export a backup, delete the Supabase account, verify cloud data is gone, and confirm local state is cleared.', features: ['backup-restore', 'account-deletion', 'cloud-sync', 'auth'], suggestionPrompt: 'Is deletion complete, recoverable only when promised, and clearly confirmed?', physicalDeviceRequired: true },
  { id: 'A30', name: 'Vikram', realLifeContext: 'Product evaluator deliberately touching every primary tab and modal', devices: 'iPhone + Apple Watch', journey: 'Complete a full week: onboarding, account, food/water/weight, Health, Coach, routine/workout/Watch, Progress, settings, sync, backup and sign-out.', features: [...FEATURE_AREAS], suggestionPrompt: 'What are the three highest-friction moments and the one missing feature that would make the app indispensable?', physicalDeviceRequired: true },
];
